/*
 * generated by Xtext 2.9.0-SNAPSHOT
 */
package org.eclipse.eXXXtreme.ui.tests;

import com.google.inject.Injector;
import org.eclipse.eXXXtreme.ui.internal.TutorialActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class TutorialUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TutorialActivator.getInstance().getInjector("org.eclipse.eXXXtreme.Tutorial");
	}

}
