/*
 * generated by Xtext 2.9.0-SNAPSHOT
 */
package org.eclipse.eXXXtreme


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TutorialStandaloneSetup extends TutorialStandaloneSetupGenerated {

	def static void doSetup() {
		new TutorialStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
