/*
 * generated by Xtext 2.9.0-SNAPSHOT
 */
package org.eclipse.eXXXtreme


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class TutorialRuntimeModule extends AbstractTutorialRuntimeModule {
}
