/*
 * generated by Xtext 2.9.0-SNAPSHOT
 */
package org.eclipse.eXXXtreme.ui;

import com.google.inject.Injector;
import org.eclipse.eXXXtreme.ui.internal.TutorialActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TutorialExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TutorialActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TutorialActivator.getInstance().getInjector(TutorialActivator.ORG_ECLIPSE_EXXXTREME_TUTORIAL);
	}
	
}
